title:        Tatterdemalion
tagline:      'Ragged writings on various things'
description:  'Stuart Popejoy's bloglocation'
url:          http://slpopejoy.github.io
version:      1.0
author:
  name:       'Stuart Popejoy'
  email:      'First Initial Last Name at Panix dot Com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
