name: Tatterdemalion
pygments: true
github: https://www.github.com/slpopejoy
about: Ragged writings on various things
# urls:
#     - text: github
#       url: https://github.com/exaem
#     - text: email
#       url: mailto:exaem@exaem.co.uk
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
