title:        tatterdemalion
tagline:      "writings by stuart popejoy"
description:  "ragged writings on various things"
url:          http://slpopejoy.github.io
version:      1.1
author:
  name:       'Stuart Popejoy'
  email:      'spopejoy-at-panix-dot-com@fix-this-email-addy.wtf'
#markdown:     rdiscount
#permalink:    pretty
#pygments:     true
#markdown:    redcarpet
#pygments: true
#markdown: kramdown
#use_coderay:   true
#coderay_css:   class
#highlighter: pygments
paginate:     5
