name: Tatterdemalion
markdown: redcarpet
pygments: true
github: https://www.github.com/slpopejoy
about: Ragged writings on various things
# urls:
#     - text: github
#       url: https://github.com/exaem
#     - text: email
#       url: mailto:exaem@exaem.co.uk
